---
- name: Enable dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    state: enabled

- name: Start dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    state: started

- name: Restart dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted